### ISSUE TITLE
speed?

### ISSUE THREAD

**Issue by hua-wu-que** [flaport/torch_sparse_solve#1]
Hi!
Thank you for this implementation. Do you have any idea on the speed compared to using torch.solve?

**Comment by flaport** [comment]
It is not so easy to unambiguously describe the performance of `torch_sparse_solve` (or any sparse solver for that matter), because this depends on *many* factors related to the specific problem *you* are working on:

* Are you working with CUDA tensors, or with CPU tensors? `torch_sparse_solve` requires a CUDA->CPU conversion (and perhaps a CPU->CUDA conversion after). These are relatively expensive operations.
* Are the sparse tensors you're working with coalesced? `torch_sparse_solve` only works for coalesced tensors. Coalescing a non-coalesced sparse tensor might be relatively expensive (depending on the size of the tensor)
* How sparse are the tensors you're working with? The more dense, the more reason to use the traditional `torch.solve`.
* How large are the sparse tensors you're working with? The smaller the tensor, the more reason to use the traditional `torch.solve`
* What is the sparsity pattern inside your sparse matrix? Some sparsity patterns turn out to be quite innefficiently solved by KLU, which in fact is mostly used in circuit simulations (which results in sparse matrices with a specific structure).

For these reasons, I do not give any specific performance metrics. Best is to just try it out for your use case and see if it is in fact faster for your specific application.
